paths:
  inputs: "00_inputs"
  data: "01_data"
  outputs: "02_outputs"
  onedrive: "C:\\Users\\Diego AB\\OneDrive - EduCorpPERU\\POSGRADO-EPEC - Panel de Control Integrado"

files:
  programacion: "PANEL DE PROGRAMACIÓN V7.xlsx"
  base_maestra_ids: "bot_blackboard/base_maestra_ids.csv"
  resumen_llave: "bot_blackboard/resumen_con_llave.csv"
  incidencias_log: "reporte_semanal/incidencias_log.csv"
  reporte_domingo: "reporte_semanal/tabla_reporte_domingo.xlsx"
  reporte_alertas: "operaciones/reporte_alertas.csv"
  reporte_grabaciones: "bot_blackboard/reporte_grabaciones.xlsx"
  separador_alertas_csv: ";"
  sepearador_incidencias_csv: ","

reporting:
  recipient: "wilbert.garate@upn.edu.pe"
  subject: "REPORTE SEMANAL SUPERVISIÓN CLASES"


dashboard:
  estilo:
    color_alerta: "red"
    color_fondo: "#1a1a2e"
    color_tarjeta: "#252545"
  textos:
    titulo_alerta: "DANGER LEVEL"
    subtitulo_alerta: "Alertas detectadas"